{{- if and (eq (include "aap-config.manifestCsiEnabled" $) "true") (eq true (default false (index ($.Values.vaultCaBundle | default dict) "enabled"))) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.vaultCaBundle.configMapName | quote }}
  namespace: {{ $.Values.ocpSecretsStoreCsiVault.secretProviderClass.namespace | default $.Values.serviceAccountNamespace | quote }}
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/ignore-differences: |
      jsonPointers:
      - /data
      jqPathExpressions:
      - .data
data: {}
{{- end }}
