{{- if and (eq .Values.aapManifest.source "externalSecret") .Values.aapManifest.createExternalSecret }}
---
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: aap-manifest
  annotations:
      argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.aapManifest.externalSecret.secretName }}
  dataFrom:
  - extract:
      key: {{ .Values.aapManifest.key }}
{{- end }}
